name: Create Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch: # enables manual trigger

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm install

      - name: Build the extension
        shell: bash
        run: npm run build

      # 🔥 Extract version from manifest.json
      - name: Extract version from manifest
        id: version
        run: |
          VERSION=$(jq -r '.version' manifest.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Zip the build directory
        run: |
          cd build
          zip -r "../youtube-mix-remover-v${VERSION}.zip" ./*

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            Release of the YouTube Automix Removal extension.
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: youtube-mix-remover-v${{ env.VERSION }}.zip
          asset_name: youtube-mix-remover-v${{ env.VERSION }}.zip
          asset_content_type: application/zip
